= chatGPT generated, form submission code

https://chatgpt.com/share/4ae93580-d820-420e-be54-4e2a628ef43b[chat gpt generated message link]

https://gist.github.com/innomon/b2a358126e121c847415f81274651e27[my github gist]

The code generated by ChatGPT did not work out of the box, had to debug it. This is the working PoC.

== Init Database
Dolt is used as the database

 innomon@raspberrypi:~/sandbox/submit-form-poc $ dolt init
 Successfully initialized dolt data repository.

Run the server

  dolt sql-server
  
open a mysql client, like BeeKeeper and create the dat table.

```sql  
CREATE DATABASE productdb;

USE productdb;

CREATE TABLE products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    sku VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    priceCurrency VARCHAR(10) NOT NULL,
    brand VARCHAR(255),
    category VARCHAR(255),
    image LONGTEXT
);

```

== Go program install

  innomon@raspberrypi:~/sandbox/submit-form-poc $ go mod init main
  go: creating new go.mod: module main
  go: to add module requirements and sums:
	go mod tidy
	
 innomon@raspberrypi:~/sandbox/submit-form-poc $ go mod tidy

Place the `index.html` inside the `static` sub-directory.
 
run the server:
  go run main.go
  
serves at localhost:8080

open the browser and point to http://localhost:8080/
  
